[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
reward_center = "rwdD3F6CgoCAoVaxcitXAeWRjQdiGc5AVABKCpQSMfd"

[programs.devnet]
reward_center = "rwdD3F6CgoCAoVaxcitXAeWRjQdiGc5AVABKCpQSMfd"

[programs.testnet]
reward_center = "rwdD3F6CgoCAoVaxcitXAeWRjQdiGc5AVABKCpQSMfd"

[programs.mainnet]
reward_center = "rwdD3F6CgoCAoVaxcitXAeWRjQdiGc5AVABKCpQSMfd"

[[test.genesis]]
address = "rwdD3F6CgoCAoVaxcitXAeWRjQdiGc5AVABKCpQSMfd"
program = "program/target/deploy/mtly_reward_center.so"

[workspace]
members = [
  "program"
]
